{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 5,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"data\": {\n",
    "      \"text/plain\": [\n",
    "       \"{'name': 'Odoo Academy',\\n\",\n",
    "       \" 'summary': 'Academy app to manage Training',\\n\",\n",
    "       \" 'description': '\\\\n    Academy Moduel to manage training: \\\\n    - Courses\\\\n    - Sessions\\\\n    - Attendees\\\\n    ',\\n\",\n",
    "       \" 'author': 'Jeremy Muniak',\\n\",\n",
    "       \" 'website': 'http://www.odoo.com/',\\n\",\n",
    "       \" 'category': 'Training',\\n\",\n",
    "       \" 'version': '0.1',\\n\",\n",
    "       \" 'depends': ['base'],\\n\",\n",
    "       \" 'data': [],\\n\",\n",
    "       \" 'demo': []}\"\n",
    "      ]\n",
    "     },\n",
    "     \"execution_count\": 5,\n",
    "     \"metadata\": {},\n",
    "     \"output_type\": \"execute_result\"\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"# A BASIC MANIFEST FILE\\n\",\n",
    "    \"\\n\",\n",
    "    \"\\n\",\n",
    "    \"# _*_ coding: utf-8 _*_\\n\",\n",
    "    \"{\\n\",\n",
    "    \"    'name': 'Odoo Academy',\\n\",\n",
    "    \"    \\n\",\n",
    "    \"    'summary': 'Academy app to manage Training',\\n\",\n",
    "    \"    \\n\",\n",
    "    \"    'description': \\\"\\\"\\\"\\n\",\n",
    "    \"    Academy Moduel to manage training: \\n\",\n",
    "    \"    - Courses\\n\",\n",
    "    \"    - Sessions\\n\",\n",
    "    \"    - Attendees\\n\",\n",
    "    \"    \\\"\\\"\\\",\\n\",\n",
    "    \"    \\n\",\n",
    "    \"    'author': 'Jeremy Muniak',\\n\",\n",
    "    \"    \\n\",\n",
    "    \"    'website': 'http://www.odoo.com/',\\n\",\n",
    "    \"    'category': 'Training',\\n\",\n",
    "    \"    'version': '0.1',\\n\",\n",
    "    \"    \\n\",\n",
    "    \"    'depends': ['base'],\\n\",\n",
    "    \"    'data': [],\\n\",\n",
    "    \"    'demo': [],\\n\",\n",
    "    \"}\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": []\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.6.9\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 4\n",
    "}\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
